#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#homepage:
#  path: /
#  controller: App\Controller\IndexController::home
add_to_cart:
    path: /cart/add/{id}
    controller: App\Controller\CartController::addToCart
cart:
    path: /cart
    controller: App\Controller\CartController::showCart
produit:
    resource: '../src/Controller/ProduitController.php'
    type: annotation
