#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#homepage:
#  path: /
#  controller: App\Controller\IndexController::home
produit:
    resource: '../src/Controller/ProduitController.php'
    type: annotation

client_login:
    path: /client/login
    controller: App\Controller\ClientSecurityController::login #  <-- CHECK THIS
client_login_check:
    path: /client/login_check
client_logout:
    path: /client/logout
client_profile:
    path: /client/profile
    controller: App\Controller\ClientSecurityController::profile
